### ISSUE TITLE
Windows winfsp support

### ISSUE THREAD

**Issue by Mitch49** [SerCeMan/jnr-fuse#16] opened 2017-03-13 08:40 UTC
Hi,

I am trying to use jnr-fuse on Windows platform with [winfsp](https://github.com/billziss-gh/winfsp). I know that there is dokany but its not stable to use.

winfsp requires additional env argument to initialize fuse properly. Here is winfsp main method:
`fsp_fuse_main_real(env, argc, argv, op, op_size, user_data)`

env requires to implement malloc and free. As far as i know `com.kenai.jffi.MemoryIO.allocateMemory` and `freeMemory` is used for native memory managment.

Also env required two additonal empty callbacks to configure winfsp properly.

What do you think about this solution? Should i use MemoryIO class?

Thanks

Here is the [releated](https://github.com/billziss-gh/winfsp/issues/60#issuecomment-285994381) issue to integrate jnr-fuse with winfsp.

**Comment by SerCeMan** [comment] 2017-03-14 02:47
Thanks, 👍  it sounds really great!

Yes, `MemoryIO` is possible. IIRC, there was another way of doing memory management; I'll take a look later today.

**Comment by SerCeMan** [comment] 2017-03-14 13:21
Apart from using `MemoryIO` directly, you can also use `jnr.ffi.Runtime.getSystemRuntime().getMemoryManager()` which has a bit more high-level interface.

**Comment by SerCeMan** [comment] 2017-03-14 13:30
> Also env required two additonal empty callbacks to configure winfsp properly.

Passing a java callback to C is simple, but calling native callback from java is trickie. I wrote a small workaround for this, `jnr.ffi.provider.jffi.ClosureHelper`. You can find an example of usage in `AbstractFuseFS:139`. 

There are also might be some problems with field sizes (alignments, offsets, etc.) because many of them defined in java.

**Comment by Mitch49** [comment] 2017-03-14 21:10
Native memory management and additional callbacks are no longer needed. With the latest patch/commit winfsp internally create the enviroment struct. Now `fuse_main_real `metod fully compitable with fuse api.

However jnr-fuse does not currently work because `getattr` behave incorrectly. I do not wan to copy-paste the eror log here. Could you please review this [issue](https://github.com/billziss-gh/winfsp/issues/60#issuecomment-286227119). Your comments will be very valuable to us.

Thanks

**Comment by SerCeMan** [comment] 2017-03-16 03:09
Hey, @Mitch49!

Sorry for the delay, I left a comment with my understanding of the problem https://github.com/billziss-gh/winfsp/issues/60#issuecomment-286945312

**Comment by gsaxena888** [comment] 2017-07-11 02:13
@SerCeMan @Mitch49 This jnr-fuse effort for winfsp could be super valuable to us. We don't have the JNR/C expertise here to help, but we can contribute a few hundred dollars bounty if that helped to get this bug resolved? It seems like it's super super close and there's just this one issue left? (We're a team of 1 founder + 5 part-time developers, but none of us know C (or JNR or Fuse) really, but we'd be happy to help test (in addition to the bounty of course.)) Might this help move this along?

**Comment by SerCeMan** [comment] 2017-07-11 10:02
Hey, @gsaxena888!

> It seems like it's super super close and there's just this one issue left? 

From what I'm aware of, it's not close. Basically, everything needs to be implemented for WinFSP/Windows and many unexpected weird issues might arise. Therefore, I can't promise anything, but I'll try to take a look at some point in time during the next week.

**Comment by gsaxena888** [comment] 2017-07-11 11:42
Awesome and thanks @SerCeMan . Please let us know if we can help test etc.

**Comment by SerCeMan** [comment] 2017-07-16 12:54
Hi, @gsaxena888!

I tried to make `jnr-fuse` and `winfps` work together, but it doesn't seem to be easy. I managed to get HelloFuse running, but the MemoryFS which is basically a litmus test for fuse doesn't work. 
But I'm not really familiar with winfsp or Windows in general, so there is a small chance that `jnr-fuse` works fine and the problem is in the FS implementation. (e.g. maybe win version requires some special flags to be set or more methods to be overridden). 

If you have a solid example that you want to test, you can try to build `jnr-fuse` from the [winfsp](https://github.com/SerCeMan/jnr-fuse/commits/winfsp) branch and test it.

**Comment by gsaxena888** [comment] 2017-07-16 16:00
@SerCeMan That's awesome (that hello-fuse works)! So, totally ignorant question on my end, but if "helloFuse" works but MemorFS doesn't, why/how could that be? As in, any more detailed hints as to where the problem lies and/or the error messages? (Again, I'm happy to help sponsor a little (eg a few hundred dollars?), since I think that jnr-fuse + winFSP is the right way to go instead of using dokan etc and programming in C).

**Comment by SerCeMan** [comment] 2017-07-17 00:44
@gsaxena888 I have no idea why :) As I said, I'm not familiar with `winfsp` or `Windows` in general, so I can't debug subtle problems. The issue might be in:

* `jnr-fuse`, It's possible that I made a subtle bug somewhere
* `winfsp`, some problem with the fuse implementation
* Memory FS, e.g. `fuse` implemented with `winfsp` might behave differently to the standard and require different flags/methods, etc...

If you are interested in the code, you can checkout the branch, run `main` from MemoryFS and try to operate on files.

**Comment by billziss-gh** [comment] 2017-07-17 20:27
@SerCeMan I am happy to help with this. Can you please let me know the specific issue you are experiencing with MemoryFS?

BTW, I am having problems even running the basic HelloFS example. The issue is with the mount point used (in the winfsp branch it is currently `C:\hello22`).

Let me briefly explain the use of mount points in WinFsp/Windows. Mount points can be:

- **Drives**. These must be of the form `X:`. WinFsp recognizes this particular format and creates a new drive `X` that can be used to access the new file system.

- **Directories**. These must of the form `X:\PATH\NON-EXISTENT-NAME`. Contrary to UNIX the directory must **not** exist prior to mounting. WinFsp will create a special "junction" directory named `NON-EXISTENT-NAME` and will mount the file system on that directory. When the file system is unmounted the directory is automatically deleted.

There seems to be some problem with `java.nio.Paths.get()` that is used to create a `Path` to feed to `AbstractFuseFS.mount()`. For example, I am unable to use `java.nio.Paths.get()` to create a "path" that contains only `X:` and I can therefore not mount on a drive. Similarly `java.nio.Paths.get()` does not seem to like non-existent directories such as `X:\PATH\NON-EXISTENT-NAME`.

[Disclaimer: I have not done any serious Java work since 2003 (other than a bit of Android). So I am obviously extremely rusty when it comes to current Java.]

**Comment by billziss-gh** [comment] 2017-07-17 20:30
BTW, I notice that MemoryFS appears to be doing case-sensitive path lookups. This works well on Windows only when mounting on drives, but not on directories. [This is a well-known Windows limitation.]

**Comment by billziss-gh** [comment] 2017-07-17 21:58
A final note: the problem with HelloFS is that I am still getting garbled strings in places like `getattr`. For example adding in beginning of `getattr`:

```java
        System.out.println("getattr: " + path);
```

results in:

```
getattr: /   W i n F s p . N e t
```

It should be `/`.

**Comment by SerCeMan** [comment] 2017-07-18 09:16
@billziss-gh Thanks for help

> I notice that MemoryFS appears to be doing case-sensitive path lookups

Yes, I also noticed that (I used directory mountpoint as you can see). But even with upper-case files, it didn't work. 

> I am still getting garbled strings

That's interesting. When I tested HW, nothing was garbled.

**Comment by billziss-gh** [comment] 2017-07-18 19:08
>@billziss-gh Thanks for help

Of course. I will gladly help to get this resolved.

>>I notice that MemoryFS appears to be doing case-sensitive path lookups
>
>Yes, I also noticed that (I used directory mountpoint as you can see). But even with upper-case files, it didn't work.

Can you be more specific? What is the exact nature of the failure you are seeing? Does the file system not work outright, does it work but is unstable, etc?

One other issue with the FUSE layer for Windows is the UNIX permissions. The UNIX permission model and Windows ACL model are fundamentally different; there is a mapping mechanism but you have to configure it properly in order to work. If you do not do so, a FUSE file system can fail in interesting ways on Windows.

>> I am still getting garbled strings
>
> That's interesting. When I tested HW, nothing was garbled.

Can this be misconfiguration of bad build on my part? I just build using `gradlew build -x test` and run it with `java -cp build\libs\jnr-fuse-0.4.2-SNAPSHOT-all.jar ru.serce.jnrfuse.examples.HelloFuse`.

During initialization of a FUSE file system there is always a `getattr` call on the `/` (root) directory to verify that the file system is accessible and get necessary information from it. This `getattr` call fails in my case because the path gets garbled. The `/` is hard-coded in the code so I am suspecting some problem with the C-Java interop layer that translates C strings to Java strings.

Here is the `getattr` call. You can see that the `/` is hard-coded.

https://github.com/billziss-gh/winfsp/blob/release/1.1/src/dll/fuse/fuse.c#L338

**Comment by billziss-gh** [comment] 2017-07-18 20:45
FYI, I am now finally able to start HelloFuse using the `-Dfile.encoding=UTF-8` option to the `java` program.

This was on a wild hunch after trying to understand some of the JNR code: [`DirectMemoryIO.getString()`](https://github.com/jnr/jnr-ffi/blob/master/src/main/java/jnr/ffi/provider/jffi/DirectMemoryIO.java#L182-L184). Notice the use of `Charset.defaultCharset()`.

**Comment by billziss-gh** [comment] 2017-07-18 21:18
I able to build and run MemoryFs using the following commands and hackpatch:

```
>gradlew.bat build -x test
>java -Dfile.encoding=UTF-8 -cp build\libs\jnr-fuse-0.4.2-SNAPSHOT-all.jar ru.serce.jnrfuse.examples.MemoryFS
```

Here is the hackpatch. It adds `open` which was missing (unfortunately this is required in current WinFsp-FUSE):

```diff
diff --git a/src/main/java/ru/serce/jnrfuse/AbstractFuseFS.java b/src/main/java/ru/serce/jnrfuse/AbstractFuseFS.java
index a9b0560..4299c95 100755
--- a/src/main/java/ru/serce/jnrfuse/AbstractFuseFS.java
+++ b/src/main/java/ru/serce/jnrfuse/AbstractFuseFS.java
@@ -232,10 +232,13 @@ public abstract class AbstractFuseFS implements FuseFS {
         }
         this.mountPoint = mountPoint;
         String[] arg;
+        String mountPointStr = mountPoint.toAbsolutePath().toString();
+        if (mountPointStr.endsWith("\\"))
+            mountPointStr = mountPointStr.substring(0, mountPointStr.length() - 1);
         if (!debug) {
-            arg = new String[]{getFSName(), "-f", mountPoint.toAbsolutePath().toString()};
+            arg = new String[]{getFSName(), "-f", mountPointStr};
         } else {
-            arg = new String[]{getFSName(), "-f", "-d", mountPoint.toAbsolutePath().toString()};
+            arg = new String[]{getFSName(), "-f", "-d", mountPointStr};
         }
         if (fuseOpts.length != 0) {
             int argLen = arg.length;
@@ -278,6 +281,8 @@ public abstract class AbstractFuseFS implements FuseFS {
     }
 
     private int execMount(String[] arg) {
+        for (int i = 0; arg.length > i; i++)
+            System.out.println(arg[i]);
         return libFuse.fuse_main_real(arg.length, arg, fuseOperations, Struct.size(fuseOperations), null);
     }
 
diff --git a/src/main/java/ru/serce/jnrfuse/examples/HelloFuse.java b/src/main/java/ru/serce/jnrfuse/examples/HelloFuse.java
index e0478ab..3964d43 100755
--- a/src/main/java/ru/serce/jnrfuse/examples/HelloFuse.java
+++ b/src/main/java/ru/serce/jnrfuse/examples/HelloFuse.java
@@ -26,6 +26,7 @@ public class HelloFuse extends FuseStubFS {
 
     @Override
     public int getattr(String path, FileStat stat) {
+        System.out.println("getattr: " + path);
         int res = 0;
         if (Objects.equals(path, "/")) {
             stat.st_mode.set(FileStat.S_IFDIR | 0755);
@@ -85,7 +86,7 @@ public class HelloFuse extends FuseStubFS {
             String path;
             switch (Platform.getNativePlatform().getOS()) {
                 case WINDOWS:
-                    path = "C:\\hello22";
+                    path = "J:\\"; //"C:\\hello22";
                     break;
                 default:
                     path = "/tmp/mnt";
diff --git a/src/main/java/ru/serce/jnrfuse/examples/MemoryFS.java b/src/main/java/ru/serce/jnrfuse/examples/MemoryFS.java
index 739e12b..841b680 100755
--- a/src/main/java/ru/serce/jnrfuse/examples/MemoryFS.java
+++ b/src/main/java/ru/serce/jnrfuse/examples/MemoryFS.java
@@ -202,7 +202,7 @@ public class MemoryFS extends FuseStubFS {
             String path;
             switch (Platform.getNativePlatform().getOS()) {
                 case WINDOWS:
-                    path = "C:\\hello22";
+                    path = "J:\\"; //C:\\hello22";
                     break;
                 default:
                     path = "/tmp/mnt";
@@ -241,6 +241,10 @@ public class MemoryFS extends FuseStubFS {
         return -ErrorCodes.ENOENT();
     }
 
+    @Override
+    public int open(String path, FuseFileInfo fi) {
+        return 0;
+    }
 
     @Override
     public int getattr(String path, FileStat stat) {
```

**Comment by SerCeMan** [comment] 2017-07-19 13:17
@billziss-gh Thanks, It looks like the `open` function did the trick. There are still some problems, but I'll try to take another look soon.

**Comment by billziss-gh** [comment] 2017-07-19 16:02
>There are still some problems, but I'll try to take another look soon.

Sure. Let me know if I can help.

**Comment by gsaxena888** [comment] 2017-08-04 11:58
Hi @SerCeMan , Just wondering if @billziss-gh 's changes mean that the jnr-fuse now works for Windows (which would be super super cool)?

**Comment by SerCeMan** [comment] 2017-08-05 06:00
Hi, @gsaxena888!

The information about the need of `open` function helped, but I'm still getting access denied on write which is very probably related to some bug in my implementation of the FileStat mapping.

**Comment by SerCeMan** [comment] 2017-08-06 12:06
Hey, @gsaxena888!

I figured out the problem, seems like winfsp requires `uid` and `gid` to be set in `getattr`. After that fix and correcting other structures, everything works as expected. I pushed changes to master. Feel free to test changes, if everything works fine, I'll release a new version.

**Comment by gsaxena888** [comment] 2017-08-06 12:30
That's phenomenal @SerCeMan ! Are there any specific "instructions" (ie a one liner etc) so that we run everything exactly the way you did so that we can test etc.?

**Comment by SerCeMan** [comment] 2017-08-06 12:35
There is no specific instruction, you will need to install `winfsp` and then you can try to run the main method from [MemoryFS](https://github.com/SerCeMan/jnr-fuse/blob/master/src/main/java/ru/serce/jnrfuse/examples/MemoryFS.java#L201) which will mount a test in-memory FS into `J:`.

**Comment by SerCeMan** [comment] 2017-08-09 09:58
@billziss-gh Do you have any experience of configuring appveyor for `winfsp`? I installed it using chocolatey, but it doesn't seem to be enough: https://github.com/SerCeMan/jnr-fuse/blob/master/appveyor.yml. Are there any particular tricks?

**Comment by nkataeva** [comment] 2017-08-09 11:48
@SerCeMan Hi, I am working for @gsaxena888 and I have run successfully MemoryFS and it mounted to `J:`. While testing it update/delete/rename/read being performed normally, but I encountered problem with uploading files to `J:`. Maybe you know what is the problem with it? Thanks in advance.

**Comment by SerCeMan** [comment] 2017-08-09 13:05
Hi, @nkataeva!

What kind of problem did you encounter? What do you mean by uploading files? You can try to take a look at the debug output; it might contain some information useful for you. Note, this concrete MemoryFS is implemented in a way that writes are quite slow.

**Comment by nkataeva** [comment] 2017-08-09 15:51
@SerCeMan for example I can copy files/folders, create archives from folders or while opening file from J: with some program save it as a new file - it all works. Once I try for example to clone project from github to `J:` or copy file from disk `C:` to `J:`. I mean I can write new files/folders within disk `J:`, but not from outer sources. Also I see that for `J:` is `0 bytes free of 0 bytes`. VM itself has 256 Gb and disk `C:` is 75 Gb (about 5 Gb of which is free), so presumably there are should be enough space. From debug output I see no errors. So I wonder is there problem with locating place for `J:` on disk?

**Comment by SerCeMan** [comment] 2017-08-13 05:06
@nkataeva I took a look and here is what I can see in logs:

```
java[TID=20fc]: FFFF9686B4A21E10: >>Create [UT---C] "\", FILE_OPEN, CreateOptions=21, FileAttributes=10, Security=NULL, AllocationSize=0:0, AccessToken=0000000000000508, DesiredAccess=100000, GrantedAccess=0, ShareAccess=3
java[TID=20fc]: FFFF9686B4A21E10: <<Create IoStatus=0[1] UserContext=0000000000000000:0000000000A0C8E0, GrantedAccess=100000, FileInfo={FileAttributes=10, ReparseTag=0, AllocationSize=0:0, FileSize=0:0, CreationTime=1970-01-01T00:00:00.000Z, LastAccessTime=1970-01-01T00:00:00.000Z, LastWriteTime=1970-01-01T00:00:00.000Z, ChangeTime=1970-01-01T00:00:00.000Z, IndexNumber=0:0}
java[TID=20fc]: FFFF9686B4A21E10: >>QueryVolumeInformation
java[TID=20fc]: FFFF9686B4A21E10: <<QueryVolumeInformation IoStatus=0[0] VolumeInfo={TotalSize=0:0, FreeSize=0:0, VolumeLabel=""}
java[TID=20fc]: FFFF9686B57C1810: >>Close 0000000000000000:0000000000A0C8E0
```

`QueryVolumeInformation` calls look suspicious. The "not enough space" on copying error is specific to windows and it's better to create an issue on `winfsp` project and ask for help there.

**Comment by billziss-gh** [comment] 2017-08-18 17:50
Hello everyone and sorry for the late response. I am on vacation.

@SerCeMan 
> @billziss-gh Do you have any experience of configuring appveyor for winfsp? I installed it using chocolatey, but it doesn't seem to be enough: https://github.com/SerCeMan/jnr-fuse/blob/master/appveyor.yml. Are there any particular tricks?

WinFsp is regularly built and tested on AppVeyor. I also run and test it on cgofuse [[appveyor.yml](https://github.com/billziss-gh/cgofuse/blob/master/.appveyor.yml)].

The `choco install winfsp -y` command should be enough. What error are you getting?

> `QueryVolumeInformation` calls look suspicious.

Windows often issues `QueryVolumeInformation` to get information about a file system. The equivalent FUSE call is `statfs`. If a file system does not implement `statfs` the WinFsp-FUSE layer returns all zeroes for `QueryVolumeInformation`.

In general this causes no problem. However perhaps the copying process does a `QueryVolumeInformation` to see if there is enough free space on the file system and aborts if it sees `0` free space. Try implementing `statfs` and see if that fixes the problem.

**Comment by webfolderio** [comment] 2017-08-19 09:15
Here is modified `MemoryFS.java`

```java
public class MemoryFS extends FuseStubFS {
    
    @Override
    public int statfs(String path, Statvfs stbuf) {
        if ("/".equals(path)) {
            stbuf.f_blocks.set(1024 * 1024); // total data blocks in file system
            stbuf.f_frsize.set(1024);        // fs block size
            stbuf.f_bfree.set(1024 * 1024);  // free blocks in fs
        }
        return super.statfs(path, stbuf);
    }
}
```

Here is how WinFSP calculate total and free size:

[fuse_intf.c](https://github.com/billziss-gh/winfsp/blob/14e6b402fe3360fdebcc78868de8df27622b565f/src/dll/fuse/fuse_intf.c#L654)


```c
VolumeInfo->TotalSize = (UINT64)stbuf.f_blocks * (UINT64)stbuf.f_frsize;
VolumeInfo->FreeSize = (UINT64)stbuf.f_bfree * (UINT64)stbuf.f_frsize;
```

Total and FreeSize still show 0.

```text
javaw[TID=12c8]: 06C82380: >>QueryVolumeInformation
javaw[TID=12c8]: 06C82380: <<QueryVolumeInformation IoStatus=0[0] VolumeInfo={TotalSize=0:0, FreeSize=0:0, VolumeLabel=""}
```

**Comment by billziss-gh** [comment] 2017-08-19 18:44
@webfolderio that's certainly curious.

@SerCeMan Could it be that the `statvfs` structure is misaligned somehow? Here is the WinFsp-FUSE definition: https://github.com/billziss-gh/winfsp/blob/master/inc/fuse/winfsp_fuse.h#L132-L162

**Comment by webfolderio** [comment] 2017-08-19 23:28
> Could it be that the statvfs structure is misaligned somehow?

good catch, this tip help me to find the problem.

I tried to test the same code with 64-bit JVM instead of a 32-bit JVM and it worked as expected. This mean that jnr-fuse is not compatible with 32-bit JVM.

**Comment by SerCeMan** [comment] 2017-08-20 14:26
Hi, @webfolderio! Sorry for the delayed response, yes, `x32` windows integration is not supported, it is possible to add it, but I'm not sure if it is worth it. Will it add much value?

**Comment by webfolderio** [comment] 2017-08-20 17:44
the following diff file fix the alignment problem for `statvfs` on 32-bit Windows environment.

> but I'm not sure if it is worth it. Will it add much value?

Multi Platform support is not an easy task. Maybe you should drop the 32-bit support for Windows environment.

```diff
 src/main/java/ru/serce/jnrfuse/struct/Statvfs.java | 43 +++++++++++++++-------
 1 file changed, 29 insertions(+), 14 deletions(-)

diff --git a/src/main/java/ru/serce/jnrfuse/struct/Statvfs.java b/src/main/java/ru/serce/jnrfuse/struct/Statvfs.java
index 7d6f711..838a237 100755
--- a/src/main/java/ru/serce/jnrfuse/struct/Statvfs.java
+++ b/src/main/java/ru/serce/jnrfuse/struct/Statvfs.java
@@ -1,7 +1,6 @@
 package ru.serce.jnrfuse.struct;
 
 import jnr.ffi.BaseStruct;
-import jnr.ffi.Struct;
 import jnr.posix.util.Platform;
 
 /**
@@ -29,19 +28,35 @@ public class Statvfs extends BaseStruct {
     public Statvfs(jnr.ffi.Runtime runtime) {
         super(runtime);
         if (Platform.IS_WINDOWS) {
-            f_bsize =  new u_int64_t();
-            f_frsize = new u_int64_t();
-            f_blocks = new fsblkcnt64_t();
-            f_bfree = new fsblkcnt64_t();
-            f_bavail = new fsblkcnt64_t();
-            f_files = new fsfilcnt64_t();
-            f_ffree = new fsfilcnt64_t();
-            f_favail = new fsfilcnt64_t();
-            f_fsid = new u_int64_t();
-            f_flag = new u_int64_t();
-            f_namemax = new u_int64_t();
-            f_unused =  null;
-            __f_spare = null;
+            if (Platform.IS_64_BIT) {
+                f_bsize =  new u_int64_t();
+                f_frsize = new u_int64_t();
+                f_blocks = new fsblkcnt64_t();
+                f_bfree = new fsblkcnt64_t();
+                f_bavail = new fsblkcnt64_t();
+                f_files = new fsfilcnt64_t();
+                f_ffree = new fsfilcnt64_t();
+                f_favail = new fsfilcnt64_t();
+                f_fsid = new u_int64_t();
+                f_flag = new u_int64_t();
+                f_namemax = new u_int64_t();
+                f_unused =  null;
+                __f_spare = null;
+            } else {
+                f_bsize =  new u_int32_t();
+                f_frsize = new u_int32_t();
+                f_blocks = new fsblkcnt64_t();
+                f_bfree = new fsblkcnt64_t();
+                f_bavail = new fsblkcnt64_t();
+                f_files = new fsfilcnt64_t();
+                f_ffree = new fsfilcnt64_t();
+                f_favail = new fsfilcnt64_t();
+                f_fsid = new u_int32_t();
+                f_flag = new u_int32_t();
+                f_namemax = new u_int32_t();
+                f_unused =  null;
+                __f_spare = null;
+            }
         } else {
             f_bsize =  new UnsignedLong();
             f_frsize = new UnsignedLong();
```

```diff
 src/main/java/jnr/ffi/BaseStruct.java | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/src/main/java/jnr/ffi/BaseStruct.java b/src/main/java/jnr/ffi/BaseStruct.java
index 4c86391..562e792 100755
--- a/src/main/java/jnr/ffi/BaseStruct.java
+++ b/src/main/java/jnr/ffi/BaseStruct.java
@@ -27,11 +27,11 @@ public abstract class BaseStruct extends Struct {
 
     public class fsblkcnt64_t extends NumberField {
         public fsblkcnt64_t() {
-            super(Platform.IS_MAC ? NativeType.UINT : NativeType.SLONGLONG);
+            super(Platform.IS_MAC ? NativeType.UINT : Platform.IS_32_BIT && Platform.IS_WINDOWS ? NativeType.SLONG : NativeType.SLONGLONG);
         }
 
         public fsblkcnt64_t(Offset offset) {
-            super(Platform.IS_MAC ? NativeType.UINT : NativeType.SLONGLONG, offset);
+            super(Platform.IS_MAC ? NativeType.UINT : Platform.IS_32_BIT && Platform.IS_WINDOWS ? NativeType.SLONG : NativeType.SLONGLONG, offset);
         }
 
         public long get() {
@@ -64,11 +64,11 @@ public abstract class BaseStruct extends Struct {
 
     public class fsfilcnt64_t extends NumberField {
         public fsfilcnt64_t() {
-            super(Platform.IS_MAC ? NativeType.UINT : NativeType.SLONGLONG);
+            super(Platform.IS_MAC ? NativeType.UINT : Platform.IS_32_BIT && Platform.IS_WINDOWS ? NativeType.SLONG : NativeType.SLONGLONG);
         }
 
         public fsfilcnt64_t(Offset offset) {
-            super(Platform.IS_MAC ? NativeType.UINT : NativeType.SLONGLONG, offset);
+            super(Platform.IS_MAC ? NativeType.UINT : Platform.IS_32_BIT && Platform.IS_WINDOWS ? NativeType.SLONG : NativeType.SLONGLONG, offset);
         }
 
         public long get() {

```

**Comment by billziss-gh** [comment] 2017-08-21 17:18
@webfolderio 
> good catch, this tip help me to find the problem.

Fantastic!

> Cross-Platform support is not an easy task. Maybe you should drop the 32-bit support for Windows environment.

IMO, it is a bit of work but it is worth doing. There are still lots of 32-bit Windows installations out there and only a few FUSE structs to fix. They are all contained in the file `winfsp_fuse.h` in the [marked lines](https://github.com/billziss-gh/winfsp/blob/master/inc/fuse/winfsp_fuse.h#L70-L171).

**Comment by SerCeMan** [comment] 2017-08-22 14:27
@nkataeva: https://github.com/SerCeMan/jnr-fuse/pull/23#issuecomment-324001753

Can you clarify what do you mean by saying this:
> I am also checking `@webfolderio` statfs method to count size.

Have you added a `statfs` method?  Is it possible that you're running `x32` jvm?

**Comment by nkataeva** [comment] 2017-08-23 09:28
As @webfolderio commented above
> Here is modified MemoryFS.java

public class MemoryFS extends FuseStubFS {
    
    @Override
    public int statfs(String path, Statvfs stbuf) {
        if ("/".equals(path)) {
            stbuf.f_blocks.set(1024 * 1024); // total data blocks in file system
            stbuf.f_frsize.set(1024);        // fs block size
            stbuf.f_bfree.set(1024 * 1024);  // free blocks in fs
        }
        return super.statfs(path, stbuf); // returns 0
    }
}

@SerCeMan I suggest there is can be problem with statfs not implemented correctly, so we get this `0 bytes free of 0 bytes` for `J:`

**Comment by billziss-gh** [comment] 2017-08-23 09:51
@nkataeva I think this is the same `struct statvfs` misalignment issue discussed earlier. See latest fix by @webfolderio.

**Comment by SerCeMan** [comment] 2017-08-23 09:55
@nkataeva Can you first confirm that you are not using `x32` jvm? `x32` is currently not supported and problems might not be limited to `statvfs` struct.

**Comment by nkataeva** [comment] 2017-08-23 10:03
@SerCeMan I checked - we are using x64.

**Comment by SerCeMan** [comment] 2017-08-23 11:54
@nkataeva I just double checked the `statvfs` implementation for `MemoryFS` provided by @webfolderio and everything as expected for me as well on the `master` branch.

**Comment by nkataeva** [comment] 2017-08-23 20:11
@SerCeMan @webfolderio Thanks for a help - jnr-fuse works well now!

**Comment by SerCeMan** [comment] 2017-08-24 11:32
@nkataeva Sounds great 🎉 !

I'm closing this issue and I'm going to release the new version. I might try to introduce support for win `x32`, but I can't promise that. It should be straightforward, but I'm sure there is more than meets the eye. E.g. some jnr structures might be incompatible with cygwin ones (I experienced that when I was working on `win x64`). 

Please open a new issue if you experience any problem.

**Closed by SerCeMan** 2017-08-24 11:32 UTC
Labels: enhancement, help wanted

**Comment by billziss-gh** [comment] 2017-08-27 13:15
@SerCeMan and everyone else fantastic work!

I am still on vacation but will close the corresponding WinFsp issue billziss-gh/winfsp#60 and will add a pointer to jnr-fuse from WinFsp.

**Comment by SerCeMan** [comment] 2017-09-04 00:17
> This jnr-fuse effort for winfsp could be super valuable to us. We don't have the JNR/C expertise here to help, but we can contribute a few hundred dollars bounty if that helped to get this bug resolved?

Hey, @gsaxena888, is it time for the abovementioned bounty?

**Comment by gsaxena888** [comment] 2017-09-06 13:39
@SerCeMan  Yes, absolutely. We're attempting to test/integrate it right now into a real project...If successful, we'll need to know best way to transfer funds etc.

**Comment by gsaxena888** [comment] 2017-09-07 13:43
@SerCeMan We're about to find out if our client has Win32 or Win64 (we're hoping for win64). If Win32, does jnr-fuse support win32 or, if planned, any timeline?

**Comment by SerCeMan** [comment] 2017-09-08 14:50
@gsaxena888 It is possible to implement x32 support, but it's hard to predict how much time it will take. I will probably not be able to look at it earlier than in a month.
